package org.lucas.Emergency.enums;


public enum PatientLocation {
    EMERGENCY_ROOM_WAITING_ROOM,
    EMERGENCY_ROOM_TRIAGE,
    EMERGENCY_ROOM_EXAMINATION_ROOM,
    EMERGENCY_ROOM_OBSERVATION_ROOM,
    EMERGENCY_ROOM_TREATMENT_ROOM,
    RADIOLOGY_XRAY_ROOM,
    ICU_ROOM,
    EMERGENCY_ROOM_DISCHARGE_AREA,
    SURGERY_ROOM;
}
