package org.lucas.Emergency.enums;


public enum PatientLocation {
    EMERGENCY_ROOM_WAITING_ROOM,
    EMERGENCY_ROOM_TRIAGE_ROOM,
    EMERGENCY_ROOM_EXAMINATION_ROOM,
    EMERGENCY_ROOM_TRAUMA_ROOM,
    EMERGENCY_ROOM_OBSERVATION_ROOM,
}
